apiVersion: apps/v1
kind: Deployment
metadata:
    name: nikcode-payments-deployment
    labels:
        app: nikcode-payments-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nikcode-payments
    template:
        metadata:
            labels:
                app: nikcode-payments
        spec:
            containers:
                - name: nikcode-payments-container
                  image: jihnordraven/nikcode-payments:latest
